name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code-
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore CMSprinkle

    - name: Build
      run: dotnet build CMSprinkle --no-restore

  unittests:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Test
      run:  dotnet test CMSprinkle.Tests\CMSprinkle.Tests.csproj --no-build --verbosity normal

  integrationtests_couchbase:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Test
      run: dotnet test CMSprinkle.Couchbase.Tests\CMSprinkle.Couchbase.Tests.csproj --no-build --verbosity normal

  integrationtests_sqlserver:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Test
      run: dotnet test CMSprinkle.SqlServer.Tests\CMSprinkle.SqlServer.Tests.csproj --no-build --verbosity normal